version: '3.8'

services:
  outline-bot:
    build: .
    container_name: outline-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
      - OUTLINE_API_URL=${OUTLINE_API_URL}
    network_mode: host
